language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_js:
  - '12'
notifications:
  email:
    recipients:
      - irvingjuarez274@gmail.com
    on_success: always
    on_failure: always
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy"
  on:
    branch: master