name: Blank
on: 
  push:
    branches: master
  workflow_dispatch:
build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello World

    - name: Run a one-line script
      run: echo Add another action to build.